def project_url = "https://github.com/micheal-itoken/itoken-config.git"
def github_auth = "ebd4cc1e-8c5d-410d-b8e0-d6a2401f9412"
node {
    def mvnHome
    stage('拉取代码') { // for display purposes
        checkout([$class: 'GitSCM', branches: [[name: '*/${branch}']],
            doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [],
            userRemoteConfigs: [[credentialsId: "${github_auth}", url: "${project_url}"]]])
    }
    stage('构建代码') {
        def workepath = $(cd $(dirname $0); pwd)
        echo '1111'
        echo $workepath
        echo '2222'
        sh "mvn clean package"
    }
    stage('Results') {
        echo 'deploy code'
    }
}