def project_url = "https://github.com/micheal-itoken/itoken-config.git"
def github_auth = "e7894059-b883-4196-9a79-c3622a5d4341"
node {
    def mvnHome
    stage('拉取代码') { // for display purposes
        checkout([$class: 'GitSCM', branches: [[name: '*/${branch}']],
            doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [],
            userRemoteConfigs: [[credentialsId: "${github_auth}", url: "${project_url}"]]])
    }
    stage('构建代码') {
        sh "mvn -f itoken-config clean install"
        sh "mvn -f ${project_name} clean package"
    }
    stage('Results') {
        echo 'deploy code'
    }
}